version: '3'
services:
    history:
        build: .
        ports:
            - "8082:8082"
        depends_on:
            - mongo
    mongo:
        image: mongo:4.4.5
        ports:
            - 27017:27017